#pragma once
#if defined(WIN64) || defined(_WIN64) || defined(__WIN64__) 
#define HashME_WindowTitle				L"HashME 1.03 x64"
#else
#define HashME_WindowTitle				L"HashME 1.03"
#endif
#ifdef CHS
#define StartError_text					L"注册窗体出错!"
#define Clear_botton_caption			L"清除"
#define Stop_botton_caption				L"停止"
#define Setting_botton_caption			L"设置"
#define About_botton_caption			L"关于"
#define Info_lable_caption				L"就绪"
#define Ucase_radbotton_caption			L"大写结果"
#define Lcase_radbotton_caption			L"小写结果"
#define Process_stopped_text			L"处理已被用户停止!"
#define Output_input_text				L"输入:\t\""
#define Output_unicode_text				L"\" 以Unicode解码\r\n"
#define Output_ansi_text				L"\" 以ANSI解码\r\n"
#define Output_utf8_text				L"\" 以UTF8解码\r\n"
#define Output_file_text				L"文件:\t"
#define Output_size_text				L"大小:\t"
#define Output_byte_text				L" 字节\r\n"
#define Output_modified_text			L"时间:\t"
#define Output_failtoread_text			L"\" 无法加载, 也许已被其他程序打开?\r\n\r\n"
#define Output_nametoolong_text			L"正在处理, 但是文件名过长无法显示...."
#define Output_processing_text			L"正在处理("
#define Output_lable_finishedtext		L"完成! 所用时间: "
#define Seconds_text					L" 秒"
#define Milliseconds_text				L" 毫秒"
#define Smaller_Than_One_text			L" 小于1毫秒"
#define Registry__error_text			L"注册表操作失败, 请以管理员运行本程序."
#else
#define StartError_text					L"Failed to register window!"
#define Clear_botton_caption			L"Clear"
#define Stop_botton_caption				L"Stop"
#define Setting_botton_caption			L"Setting"
#define About_botton_caption			L"About"
#define Info_lable_caption				L"Ready"
#define Ucase_radbotton_caption			L"Uppercase"
#define Lcase_radbotton_caption			L"Lowercase"
#define Process_stopped_text			L"Processing is stopped by user!"
#define Output_input_text				L"Input:\t\""
#define Output_unicode_text				L"\" decoding as Unicode\r\n"
#define Output_ansi_text				L"\" decoding as ANSI\r\n"
#define Output_utf8_text				L"\" decoding as UTF8\r\n"
#define Output_file_text				L"File:\t"
#define Output_size_text				L"Size:\t"
#define Output_byte_text				L" bytes\r\n"
#define Output_modified_text			L"Modified:\t"
#define Output_failtoread_text			L"\" fail to read. Opened in another program?\r\n\r\n"
#define Output_nametoolong_text			L"Processing but filename too long to show...."
#define Output_processing_text			L"Processing("
#define Output_lable_finishedtext		L"Done! Time used: "
#define Seconds_text					L" seconds"
#define Milliseconds_text				L" milliseconds"
#define Smaller_Than_One_text			L" smaller than 1 millisecond"
#define Registry__error_text			L"Registry opration failed. Please run as Administrator."
#endif